import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DAppProvider from "@/providers/DAppProvider";
import ConnectButton from "@/components/connect-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To do list ETH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <DAppProvider>
          <header>
            <ConnectButton />
          </header>
          {children}
        </DAppProvider>
      </body>
    </html>
  );
}
